c_compiler_version: # works in conjunction with c_stdlib_version
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]
  - 11          # [linux and aarch64]
  - 11          # [linux and x86_64]

cxx_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]
  - 11          # [linux and aarch64]
  - 11          # [linux and x86_64]

c_stdlib_version:
  - 2.28        # [linux and aarch64]
  - 2.28        # [linux and x86_64]
  - 2.28        # [linux and aarch64]
  - 2.17        # [linux and x86_64]

fortran_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]
  - 11          # [linux and aarch64]
  - 11          # [linux and x86_64]

cuda_compiler_version:
  - 12.0        # [linux and aarch64]
  - 12.0        # [linux and x86_64]
  - 12.0        # [win]
  - 11.8        # [linux and aarch64]
  - 11.8        # [linux and x86_64]
  - 11.8        # [win]

cuda_compiler:
  - cuda-nvcc   # [linux and aarch64]
  - cuda-nvcc   # [linux and x86_64]
  - cuda-nvcc   # [win]
  - nvcc        # [linux and aarch64]
  - nvcc        # [linux and x86_64]
  - nvcc        # [win]

cdt_name:
  - cos7        # [linux and aarch64]
  - cos7        # [linux and x86_64]
  - cos7        # [linux and aarch64]
  - cos7        # [linux and x86_64]

docker_image:
  - quay.io/condaforge/linux-anvil-alma-aarch64:8     # [linux and aarch64] # glibc 2.28
  - quay.io/condaforge/linux-anvil-alma-x86_64:8      # [linux and x86_64]  # glibc 2.28
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.8  # [linux and aarch64] # glibc 2.28
  - quay.io/condaforge/linux-anvil-cuda:11.8          # [linux and x86_64]  # glibc 2.17

