conda_forge_output_validation: true
provider:
  linux_aarch64: azure
build_platform:
  linux_aarch64: linux_64
# NOTE: For binary redists os_version should match oldest supported glibc
os_version:
  linux_64: alma8
  linux_aarch64: alma8
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
